# product-service.yml
server:
  port: 8081


info:
    app:
      description: "descripcion hola "

spring:
  application:
    name: product-service
  datasource:
    url: jdbc:h2:mem:productdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
